---
title: "Shark Attacks in Australia"
date: "12/11/2024"
authors: "Erica Loomis (esloom25), Timothy Pratt (tjprat25), and Rebecca Wanger (rswang25)"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r}
## Connecting to the Shiny App Account
rsconnect::setAccountInfo(name='ter1',
			  token='0163EF6118B243DE8D0042631C039930',
			  secret='<Secret>')

## Actually running and deploying the app

library(shiny)
library(ggplot2)
#runApp()

#deploying the app

library(rsconnect)
#deployApp()

#link: https://ter1.shinyapps.io/sc326-tre-interactive-graphics-project/
```


Introduction: You Won a Trip to Australia!
=====================================  

```{r global, include=FALSE, warning=FALSE, message=FALSE}
# loading in data in 'global' chunk so it can be shared by all users of the dashboard
shark_attacks <- read.csv("Shark Dataset.csv")

# load packages in 'global' chunk so they can be shared by all users of the dashboard
library(httr2)
library(purrr)
library(tibble)
library(lubridate)
library(dplyr)
library(ggplot2)
library(shiny)
library(tidyr)
library(ggseas) #to use stat_rollapplyr
```


How Have Shark Attacks Changed over Time?
=====================================  

Column {.sidebar}
-----------------------------------------------------------------------
