---
title: "REBECCA Practice"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r global, include=FALSE, warning=FALSE, message=FALSE}
# loading in data in 'global' chunk so it can be shared by all users of the dashboard
shark_attacks <- read.csv("Shark Dataset.csv")

# load packages in 'global' chunk so they can be shared by all users of the dashboard
library(httr2)
library(purrr)
library(tibble)
library(lubridate)
library(dplyr)
library(ggplot2)
library(shiny)
library(tidyr)
library(ggseas) #to use stat_rollapplyr
library(plotly)
library(forcats)

interactive_theme <- theme_gray() +# White background, black and white theme
  theme(plot.title = element_text(family = "Georgia", face = "bold", color = "#0a144a"),
        axis.title = element_text(family = "DIN Alternate", color = "#0a144a"),
        axis.text = element_text(color = "#0a144a"),
        legend.title = element_text(family = "DIN Alternate", face = "bold",  color = "#0a144a"),
        legend.text = element_text(family = "DIN Alternate", color = "#0a144a"),
        legend.box.margin = margin(6, 6, 6, 6),
        legend.background = element_rect(fill = "#d1d4e3"),
        panel.background = element_rect(fill = "#d1d4e3"),
        plot.background = element_rect(fill = "#d1d4e3"))
```

How Have Shark Attacks Changed Over Time?
=====================================  

```{r global_time, include=FALSE, warning=FALSE, message=FALSE}

# load packages in 'global' chunk so they can be shared by all users of the dashboard
library(httr2)
library(purrr)
library(tibble)
library(lubridate)
library(dplyr)
library(ggplot2)
library(shiny)
library(tidyr)
library(ggseas) #to use stat_rollapplyr
library(plotly)

#loading in packages related to the maps
library(stringr) #to use str functions
library(sf)
library(maps)

# Loading in the Data and Packages

shark_attacks <- read.csv("Australian Shark-Incident Database Public Version.csv")



# reading in the Australian state shapefiles

load("aus_shp.RData")
  #st_read("./STE_2021_AUST_SHP_GDA94/STE_2021_AUST_GDA94.shp")



```


```{r}

# cleaning the data

#adding in means, renaming and recategorizing, 
shark_attacks <- shark_attacks %>%
  filter(is.na(UIN) != T) %>% #removing the empty rows
  mutate(Victim.injury = case_when(Victim.injury == "fatal" ~ "Fatal",
                                   Victim.injury == "injured" ~ "Injured",
                                   Victim.injury == "Injured" ~ "Injured",
                                   Victim.injury == "uninjured" ~ "Uninjured")) %>%
  mutate(Provoked.unprovoked = case_when(Provoked.unprovoked == "provoked" ~ "Provoked",
                                   Provoked.unprovoked == "unprovoked" ~ "Unprovoked")) %>%
  mutate(Victim.gender = case_when(Victim.gender == "female" ~ "Female",
                                   Victim.gender == "male" ~ "Male")) %>%
  mutate(Injury.severity = case_when(Injury.severity == "abrasion" ~ "Abrasion", Injury.severity == "major lacerations" ~ "Major Lacerations", Injury.severity == "minor lacerations" ~ "Minor Lacerations", Injury.severity == "other: teeth marks" ~ "Other: Teeth Marks", Injury.severity == "punctures" ~ "Punctures", Injury.severity == "surface wound" ~ "Surface Wound")) %>%
  mutate(Site.category = case_when(Site.category == "coastal" ~ "Coastal",
                                   Site.category == "Coastal" ~ "Coastal",
                                   Site.category == "estuary/harbour" ~ "Estuary/Harbour", 
                                   Site.category == "island open ocean" ~ "Island Open Ocean", 
                                   Site.category == "ocean/pelagic" ~ "Ocean/Pelagic",
                                   Site.category == "other: fish farm" ~ "Other",
                                   Site.category == "river" ~ "River",
                                   is.na(Site.category) ~ "Other")) %>%
  mutate(Site.category = as.factor(Site.category)) %>%
  filter(Incident.year != "1791") %>%
  mutate(Victim.activity = case_when(Victim.activity == "boarding" ~ "Boarding",
                                   Victim.activity == "diving" ~ "Diving",
                                   Victim.activity == "diving, collecting" ~ "Diving",
                                   Victim.activity == "fishing" ~ "Fishing",
                                   Victim.activity == "motorised boating" ~ "Motorised Boating",
                                   Victim.activity == "other: standing in water" ~ "Standing in Water",
                                   Victim.activity == "other: hull scraping" ~ "Other",
                                   Victim.activity == "other: jetskiing; swimming" ~ "Other",
                                   Victim.activity == "other:floating" ~ "Swimming",
                                   Victim.activity == "wing foiler" ~ "Other",
                                   Victim.activity == "snorkeling" ~ "Snorkeling", 
                                   Victim.activity == "surfing" ~ "Boarding",
                                   Victim.activity == "snorkelling" ~ "Snorkeling",
                                   Victim.activity == "spearfishing" ~ "Spearfishing",
                                   Victim.activity == "paddleboarding" ~ "Boarding",
                                   Victim.activity == "swimming" ~ "Swimming",
                                   Victim.activity == "unmotorised boating" ~ "Boating",
                                   Victim.activity == "" ~ NA)) %>%
  
  filter(Incident.year != "1791") %>%
  group_by(Incident.year) %>%
   #creating mean columns
  mutate(Victim.age.mean = mean(Victim.age)) %>%
  #creating date groupings
  mutate(Year = case_when((Incident.year > 1800 & Incident.year <= 1850) ~ "1800-1850", 
                          (Incident.year > 1850 & Incident.year <= 1900) ~ "1850-1900",
                          (Incident.year > 1900 & Incident.year <= 1950) ~ "1900-1950",
                          (Incident.year > 1950 & Incident.year <= 2000) ~ "1950-2000",
                          (Incident.year > 2000 & Incident.year <= 2024) ~ "2000-2024")) 

#counting the number of sharks every 50 years
shark_attacks <- shark_attacks %>%
  group_by(Year) %>%
  mutate(Number_Attacks = n())

```

```{r}
#creating a dataframe for timeline data
shark_attacks_timeline <- shark_attacks %>%
  mutate(Victim.age = as.ts(Victim.age)) %>% 
  mutate(Incident.month = as.character(Incident.month)) %>% 
  mutate(Incident.year = as.character(Incident.year)) %>%
  mutate(Incident.year = make_date(year = Incident.year))
  # unite("Incident.month_year", Incident.month, Incident.year, sep = "/", remove = F) %>% #remove = F, na.rm = T
  # mutate(Incident.month_year = paste0("01/", Incident.month_year),
  #        Incident.month_year = as.Date(Incident.month_year, format = "%d/%m/%Y"))
  # 
#start and stop times

start_time <- as.Date("1800-01-01")
end_time <- as.Date("2024-01-01")


start.end <- c(start_time, end_time)

shark_attacks_count <- shark_attacks_timeline %>%
  group_by(Incident.year) %>%
  summarise(attack_count = n()) %>%
  mutate(Incident.year = as.Date(Incident.year, format = "%Y"))

```

```{r}

# computing proportions individually

#individually

#Victim.injury
shark_attacks_proportions_Victim.injury <- shark_attacks %>%  #  Start with the cereal data.frame
  filter(Victim.injury != "") %>%
  group_by(Year, Victim.injury) %>%  #  group by the year variable
  summarise(count_Victim.injury = n()) %>% 
  mutate(total_Victim.injury = sum(count_Victim.injury),  #  compute total number of observations
         proportion_Victim.injury = count_Victim.injury / total_Victim.injury,  #  compute proportions
         std_error_Victim.injury = sqrt(proportion_Victim.injury * (1-proportion_Victim.injury) / total_Victim.injury),  #  compute standard error of each proportion
         lower_Victim.injury = proportion_Victim.injury - 1.96 * std_error_Victim.injury,  #  compute CI lower bound
         upper_Victim.injury = proportion_Victim.injury + 1.96 * std_error_Victim.injury) 
  

#Site.category
shark_attacks_proportions_Site.category <- shark_attacks %>%  #  Start with the cereal data.frame
  filter(Site.category != "") %>%
  group_by(Year, Site.category) %>%  #  group by the year variable
  summarise(count_Site.category = n()) %>%  
  mutate(total_Site.category = sum(count_Site.category),  
         proportion_Site.category = count_Site.category / total_Site.category,  
         std_error_Site.category = sqrt(proportion_Site.category * (1-proportion_Site.category) / total_Site.category),  
         lower_Site.category = proportion_Site.category - 1.96 * std_error_Site.category,  
         upper_Site.category = proportion_Site.category + 1.96 * std_error_Site.category) 



#Provoked.unprovoked
shark_attacks_proportions_Provoked.unprovoked <- shark_attacks %>%  #  Start with the cereal data.frame
  filter(Provoked.unprovoked != "") %>%
  group_by(Year, Provoked.unprovoked) %>%  #  group by the year variable
  summarise(count_Provoked.unprovoked = n()) %>%  
  mutate(total_Provoked.unprovoked = sum(count_Provoked.unprovoked),  
         proportion_Provoked.unprovoked = count_Provoked.unprovoked / total_Provoked.unprovoked, 
         std_error_Provoked.unprovoked = sqrt(proportion_Provoked.unprovoked * (1-proportion_Provoked.unprovoked) / total_Provoked.unprovoked),  
         lower_Provoked.unprovoked = proportion_Provoked.unprovoked - 1.96 * std_error_Provoked.unprovoked,  
         upper_Provoked.unprovoked = proportion_Provoked.unprovoked + 1.96 * std_error_Provoked.unprovoked)
  

#Victim.activity
shark_attacks_proportions_Victim.activity <- shark_attacks %>%  #  Start with the cereal data.frame
  filter(Victim.activity != "") %>%
  group_by(Year, Victim.activity) %>%  #  group by the year variable
  summarise(count_Victim.activity = n()) %>%  
  mutate(total_Victim.activity = sum(count_Victim.activity),  
         proportion_Victim.activity = count_Victim.activity / total_Victim.activity,  
         std_error_Victim.activity = sqrt(proportion_Victim.activity * (1-proportion_Victim.activity) / total_Victim.activity),  
         lower_Victim.activity = proportion_Victim.activity - 1.96 * std_error_Victim.activity,
         upper_Victim.activity = proportion_Victim.activity + 1.96 * std_error_Victim.activity)


#Victim.gender 
shark_attacks_proportions_Victim.gender <- shark_attacks %>% #  Start with the data.frame
  filter(Victim.gender != "") %>%
  group_by(Year, Victim.gender) %>%  #  group by the year variable
  summarise(count_Victim.gender = n()) %>%    
  mutate(total_Victim.gender = sum(count_Victim.gender),  
         proportion_Victim.gender = count_Victim.gender / total_Victim.gender,  
         std_error_Victim.gender = sqrt(proportion_Victim.gender * (1-proportion_Victim.gender) / total_Victim.gender), 
         lower_Victim.gender = proportion_Victim.gender - 1.96 * std_error_Victim.gender,  
         upper_Victim.gender = proportion_Victim.gender + 1.96 * std_error_Victim.gender)
  
  
#Injury.severity
shark_attacks_proportions_Injury.severity <- shark_attacks %>%  #Start with the cereal data.frame
  filter(Injury.severity != "") %>%
  group_by(Year, Injury.severity) %>%  #  group by the year variable
  summarise(count_Injury.severity = n()) %>%  
  mutate(total_Injury.severity = sum(count_Injury.severity),  
         proportion_Injury.severity = count_Injury.severity / total_Injury.severity,  
         std_error_Injury.severity = sqrt(proportion_Injury.severity * (1-proportion_Injury.severity) / total_Injury.severity), 
         lower_Injury.severity = proportion_Injury.severity - 1.96 * std_error_Injury.severity,  
         upper_Injury.severity = proportion_Injury.severity + 1.96 * std_error_Injury.severity) 





```

### Shark Attacks over Time

Row {data-height=200}
-----------------------------------------------------------------------

### Based on these results, it appears that...

The number of attacks and the age of people being attacked is increasing over time! Although, fortunately, the proportion of fatal attacks over time is decreasing. 

Unfortunately, unprovoked attacks seem to occur more than provoked attacks and both are increasing over time. 

If you are male, good luck! Throughout time, every 50 years, over ~80% of attacks occur with male victims. 

While fatalities and major lacerations in association with shark attacks are decreasing, minor lacerations are increasing in proportion. 

As for location, most of the attacks over time have also occurred coastally, and the proportion of the coastal attacks is increasing over time while the proportion of the attacks further out to sea or inland are decreasing or stagnant. 

As for activities, swimming appeared to be more dangerous in the past up until the 2000s when boarding became more risky. Snorkeling, spearfishing, and diving are also slightly risky activities but in recent decades, less than 30% of shark attacks are associated to these activities. It also should be noted that even standing the water can be dangerous, with over 1% of shark attacks being attributed to standing in water every 50 years since the early 1900s. 



Row 
-----------------------------------------------------------------------

### Shark Attacks over Time


```{r}


dataframe_barchart <- reactive({switch(input$response_var,
                    "Victim.injury" = shark_attacks_proportions_Victim.injury,
                    "Site.category" = shark_attacks_proportions_Site.category,
                    "Provoked.unprovoked" = shark_attacks_proportions_Provoked.unprovoked,
                    "Victim.activity" = shark_attacks_proportions_Victim.activity,
                    "Injury.severity" = shark_attacks_proportions_Injury.severity,
                     "Victim.gender" = shark_attacks_proportions_Victim.gender)
})

dataframe_time <- reactive({switch(input$response_var,
                    "Victim.age" = shark_attacks_timeline,
                    "attack_count" = shark_attacks_count)
})

lineplot <- c("Victim.age", "attack_count")
barchart <- c("Victim.injury", "Site.category", "Provoked.unprovoked", "Victim.activity", "Injury.severity", "Victim.gender")


# try changing the categories to x axis and time to color
#jerzy prefer's the line and point graphs

renderPlotly({
  if(input$response_var %in% barchart){
    
    dataframe_barchart_ordered <- dataframe_barchart() %>%
      mutate(!!sym(input$response_var) := factor(!!sym(input$response_var), 
        levels = if (input$response_var == "Victim.injury") {
          c("Fatal", "Injured", "Uninjured")
        } else if (input$response_var == "Site.category") {
          c("Ocean/Pelagic", "Island Open Ocean", "Estuary/Harbour", "Coastal", "River", "Other")
        } else if (input$response_var == "Provoked.unprovoked") {
          c("Provoked", "Unprovoked")
        } else if (input$response_var == "Victim.activity") {
          c("Boarding", "Boating", "Diving", "Fishing", "Motorised Boating", "Other", "Snorkeling", "Spearfishing", "Standing in Water", "Swimming")
        } else if (input$response_var == "Injury.severity") {
          c("Major Lacerations", "Minor Lacerations", "Punctures", "Surface Wound", "Abrasion", "Other: Teeth Marks")
        } else if (input$response_var == "Victim.gender") {
          c("Male", "Female")
        } else {
          NULL
        }
      ))
    barchart_plot <- ggplot(dataframe_barchart_ordered, 
                            aes_string(y = ifelse(input$prop_count == "prop", paste0("proportion_", input$response_var), ifelse(input$prop_count == "count", paste0("count_", input$response_var), NULL)),  fill = input$response_var, color = input$response_var)) +
      geom_line(aes_string(x = "Year", group = input$response_var, color = input$response_var))+
      geom_point(aes(x = Year))+
         labs(x = "Years",
              y = ifelse(input$prop_count == "prop", "Proportion","Count"), 
              title = list(text = paste0(paste0(paste0(ifelse(input$prop_count == "prop", "Proportion", "Count"),
                paste0(ifelse(input$response_var == "Victim.injury", " of Victim Injury Type Over Time", ifelse(input$response_var == "Site.category", " of Shark Attack Site Categories Over Time", ifelse(input$response_var == "Provoked.unprovoked", " of Provoked vs. Unprovoked Shark Attacks Over Time", ifelse(input$response_var == "Victim.activity", " of Victim Activities Over Time", ifelse(input$response_var == "Injury.severity", " of Injurity Severity Over Time", ifelse(input$response_var == "Victim.gender", " of Victim Genders Over Time", ""))))))))), '<br>',
                                    '<sup>',
                                     '  Error Bars show 95% Confidence Intervals, Dates are by 50 Years except for 2000-2024','</sup>')),
               # subtitle = "Error Bars show 95% Confidence Interval\nDates are by 50 Years except for 2000-2024",
              fill = ifelse(input$response_var == "Victim.injury", "Victim Injuries", ifelse(input$response_var == "Site.category", "Site Categories", ifelse(input$response_var == "Provoked.unprovoked", "Provoked?", ifelse(input$response_var == "Victim.activity", "Victim Activities", ifelse(input$response_var == "Injury.severity", "Injurity Severity", ifelse(input$response_var == "Victim.gender", "Victim Gender", "")))))),
              color = ifelse(input$response_var == "Victim.injury", "Victim Injuries", ifelse(input$response_var == "Site.category", "Site Categories", ifelse(input$response_var == "Provoked.unprovoked", "Provoked?", ifelse(input$response_var == "Victim.activity", "Victim Activities", ifelse(input$response_var == "Injury.severity", "Injurity Severity", ifelse(input$response_var == "Victim.gender", "Victim Gender", ""))))))) +
      scale_color_manual(values = c("Fatal" = "#a50f15", "Injured" = "#ef3b2c", "Uninjured" = "#fcbba1", "Ocean/Pelagic" = "#343d6f", "Island Open Ocean" = "#045a8d", "Estuary/Harbour" = "#2b8cbe", "Coastal" = "#74a9cf",  "River" = "#a6bddb", "Other" = "#969696","Provoked" = "#8c3a40", "Unprovoked" = "#343d6b", "Swimming" = "#a6cee3", "Boarding" = "#1f78b4", "Spearfishing" = "#b2df8a", "Snorkeling" = "#33a02c", "Diving" = "#fb9a99", "Boating" = "#e31a1c", "Standing in Water" = "#fdbf6f", "Fishing" = "#ff7f00", "Other" = "#cab2d6",
          "Major Lacerations" = "#a50f15", "Minor Lacerations" = "#de2d26", "Punctures" = "#fb6a4a" , "Surface Wound" = "#fc9272", "Abrasion" = "#fcbba1", "Other: Teeth Marks" = "#fee5d9", "Male" = "#a6cee3", "Female" = "#fb9a99"),
           labels = c("Fatal", "Injured", "Uninjured", "Ocean/Pelagic", "Island Open Ocean", "Estuary/Harbour", "Coastal", "River", "Other","Provoked", "Unprovoked", "Swimming", "Boarding", "Spearfishing", "Snorkeling", "Diving", "Boating", "Standing in Water", "Fishing", "Other", "Major Lacerations", "Minor Lacerations", "Punctures", "Surface Wound", "Abrasion", "Other: Teeth Marks", "Male", "Female"))+

       scale_fill_manual(values = c("Fatal" = "#a50f15", "Injured" = "#ef3b2c", "Uninjured" = "#fcbba1", "Ocean/Pelagic" = "#343d6b", "Island Open Ocean" = "#045a8d", "Estuary/Harbour" = "#2b8cbe", "Coastal" = "#74a9cf",  "River" = "#a6bddb", "Other" = "#969696","Provoked" = "#8c3a40", "Unprovoked" = "#343d6b", "Swimming" = "#a6cee3", "Boarding" = "#1f78b4", "Spearfishing" = "#b2df8a", "Snorkeling" = "#33a02c", "Diving" = "#fb9a99", "Boating" = "#e31a1c", "Standing in Water" = "#fdbf6f", "Fishing" = "#ff7f00", "Other" = "#cab2d6",
          "Major Lacerations" = "#a50f15", "Minor Lacerations" = "#de2d26", "Punctures" = "#fb6a4a" , "Surface Wound" = "#fc9272", "Abrasion" = "#fcbba1", "Other: Teeth Marks" = "#fee5d9", "Male" = "#a6cee3", "Female" = "#fb9a99"),
          labels = c("Fatal", "Injured", "Uninjured", "Ocean/Pelagic", "Island Open Ocean", "Estuary/Harbour", "Coastal", "River", "Other","Provoked", "Unprovoked", "Swimming", "Boarding", "Spearfishing", "Snorkeling", "Diving", "Boating", "Standing in Water", "Fishing", "Other", "Major Lacerations", "Minor Lacerations", "Punctures", "Surface Wound", "Abrasion", "Other: Teeth Marks", "Male", "Female"))+
      interactive_theme +
      theme(legend.position = "bottom")

     # Add error bars if selected
  if (input$error_bar & input$prop_count == "prop") {
    barchart_plot <- barchart_plot +
      geom_errorbar(data = dataframe_barchart_ordered, 
                    aes_string(x = "Year", 
                               ymin = paste0("lower_", input$response_var), 
                               ymax = paste0("upper_", input$response_var), 
                               color =  input$response_var), 
                    position = position_dodge(preserve = "single")) + # position_dodge(0.9)) #position = "dodge") #position_dodge(preserve = "single")
          geom_point(aes(x = Year))
    
  } 
    
# Define tooltip based on the response variable
    tooltip_text <- ""

    if (input$prop_count == "prop") {
      tooltip_text <- switch(input$response_var,
                             "Victim.injury" = paste0("<br>Victim Injury: ", dataframe_barchart_ordered$Victim.injury,"<br>Proportion: ", dataframe_barchart_ordered$proportion_Victim.injury,"<br>Lower Proportion: ", dataframe_barchart_ordered$lower_Victim.injury,"<br>Upper Proportion: ", dataframe_barchart_ordered$upper_Victim.injury,"<br>Years: ", dataframe_barchart_ordered$Year),
                             "Site.category" = paste0("<br>Site Category: ", dataframe_barchart_ordered$Site.category,"<br>Proportion:", dataframe_barchart_ordered$proportion_Site.category, "<br>Lower Proportion: ", dataframe_barchart_ordered$lower_Site.category,"<br>Upper Proportion: ", dataframe_barchart_ordered$upper_Site.category, "<br>Years: ", dataframe_barchart_ordered$Year),
                             "Provoked.unprovoked" = paste0("<br>Provoked?: ", dataframe_barchart_ordered$Provoked.unprovoked,"<br>Proportion: ", dataframe_barchart_ordered$proportion_Provoked.unprovoked,"<br>Lower Proportion: ", dataframe_barchart_ordered$lower_Provoked.unprovoked,"<br>Upper Proportion: ", dataframe_barchart_ordered$upper_Provoked.unprovoked,"<br>Years: ", dataframe_barchart_ordered$Year),
                             "Victim.activity" = paste0("<br>Victim Activity: ", dataframe_barchart_ordered$Victim.activity, "<br>Proportion: ", dataframe_barchart_ordered$proportion_Victim.activity,"<br>Lower Proportion: ", dataframe_barchart_ordered$lower_Victim.activity,"<br>Upper Proportion: ", dataframe_barchart_ordered$upper_Victim.activity, "<br>Years: ", dataframe_barchart_ordered$Year),
                             "Injury.severity" = paste0("<br>Injury Severity: ", dataframe_barchart_ordered$Injury.severity, "<br>Proportion: ", dataframe_barchart_ordered$proportion_Injury.severity,"<br>Lower Proportion: ", dataframe_barchart_ordered$lower_Injury.severity,"<br>Upper Proportion: ", dataframe_barchart_ordered$upper_Injury.severity,"<br>Years: ", dataframe_barchart_ordered$Year),
                             "Victim.gender" = paste0("<br>Victim Gender: ", dataframe_barchart_ordered$Victim.gender, "<br>Proportion: ", dataframe_barchart_ordered$proportion_Victim.gender, "<br>Lower Proportion: ", dataframe_barchart_ordered$lower_Victim.gender,"<br>Upper Proportion: ", dataframe_barchart_ordered$upper_Victim.gender,"<br>Years: ", dataframe_barchart_ordered$Year),
                             NULL)
    } else {
      tooltip_text <- switch(input$response_var,
                             "Victim.injury" = paste0("<br>Victim Injury: ", dataframe_barchart_ordered$Victim.injury, "<br>Count: ", dataframe_barchart_ordered$count_Victim.injury,
                                                      "<br>Years: ", dataframe_barchart_ordered$Year),
                             "Site.category" = paste0("<br>Site Category: ", dataframe_barchart_ordered$Site.category, "<br>Count: ", dataframe_barchart_ordered$count_Site.category,
"<br>Years: ", dataframe_barchart_ordered$Year),
                             "Provoked.unprovoked" = paste0("<br>Provoked?: ", dataframe_barchart_ordered$Provoked.unprovoked, "<br>Count: ", dataframe_barchart_ordered$count_Provoked.unprovoked, "<br>Years: ", dataframe_barchart_ordered$Year),
                             "Victim.activity" = paste0("<br>Victim Activity: ", dataframe_barchart_ordered$Victim.activity,"<br>Count: ", dataframe_barchart_ordered$count_Victim.activity,
                                                       "<br>Years: ", dataframe_barchart_ordered$Year),
                             "Injury.severity" = paste0("<br>Injury Severity: ", dataframe_barchart_ordered$Injury.severity,"<br>Count: ", dataframe_barchart_ordered$count_Injury.severity,
                                                        "<br>Years: ", dataframe_barchart_ordered$Year),
                             "Victim.gender" = paste0("<br>Victim Gender: ", dataframe_barchart_ordered$Victim.gender,"<br>Count: ", dataframe_barchart_ordered$count_Victim.gender,
                                                      "<br>Years: ", dataframe_barchart_ordered$Year),
                             NULL)
    }

    # Add tooltip_text to the plot
    barchart_plot <- barchart_plot + aes(text = tooltip_text)
    
    return(ggplotly(barchart_plot, tooltip = "text"))

    
  } else if (input$response_var %in% lineplot) {
    lineplot_plot <- ggplot(data = dataframe_time(),
                            aes_string(x = "Incident.year", y = input$response_var)) +
        geom_point(alpha = 0.6, size = 0.8) +
        geom_smooth(method = "loess", alpha = 0.2, color = alpha("blue", 0.3)) +
        labs(x = "Date", 
             y = ifelse(input$response_var == "attack_count", "Number of Attacks", "Victim Age"),
             title = ifelse(input$response_var ==  "Victim.age", "Victim Age per Attack during Shark Attacks between 1800-2024", ifelse(input$response_var == "attack_count", "Number of Australian Shark Attacks per Year between 1800-2024", ""))) +
        #     scale_x_continuous(
        #     breaks = seq(1800, 2024, by = 10), # Set specific breaks
        #     labels = seq(1800, 2024, by = 10), # Label years explicitly
        #     limits = c(1800, 2024) # Specify numeric limits
        # ) +
       scale_x_date(date_breaks = "10 years", date_labels = ifelse(input$response_var == "attack_count", "%Y", "%Y"), limits = start.end) +

      #ifelse(input$response_var == "attack_count", "%Y", "%Y")
      # scale_x_continuous(
      #       breaks = seq(1800, 2024, by = 10),
      #       labels = as.character(seq(1800, 2024, by = 10)),
      #       limits = c(1800, 2024)
      #   ) +
      # coord_cartesian(xlim = as.Date(c("1800-01-01", "2024-01-01"))) +
          # coord_cartesian(xlim = c(as_date(1800, 2024))) +
  # coord_cartesian(xlim=c(as_date("1800-01-01","2024-03-01")))+
    
    
#     start_time <- as.Date("1800-01-01")
# end_time <- as.Date("2024-03-01")
#       xlim(c("1800", "2024")) + 
        #stat_rollapplyr(width = 50, align = "right", linewidth = 1, color = "red") +
        theme(axis.text.x = element_text(angle = 45, vjust = 0.8)) +
      interactive_theme
    
    # # Define tooltip based on the response variable
    # tooltip_text_date <- ""
    # 
    # if (input$response_var == "attack_count") {
    #   tooltip_text_date = paste0("<br>Attack Count: ", shark_attacks_count$attack_count,
    #                                                   "<br>Year: ", shark_attacks_count$Incident.year)
    # } else {
    #    tooltip_text_date = paste0("<br>Victim Age: ", shark_attacks_timeline$Victim.age,
    #                                                   "<br>Year: ", shark_attacks_timeline$Incident.year)
    # }
    # 
    # 
    #     # Add tooltip_text to the plot
    # lineplot_plot <- lineplot_plot + aes(text = tooltip_text_date) 
    # 
    # return(ggplotly(lineplot_plot, tooltip = "text"))


    return(ggplotly(lineplot_plot))
  
   
  }
  
})


```



Column {.sidebar}
-----------------------------------------------------------------------



```{r}


#widgets for the barcharts

radioButtons("response_var", label = h3("Attack Characteristic:"), 
    choices = list("Number of Attacks" = "attack_count", "Victim Age" = "Victim.age", "Provoked?" = "Provoked.unprovoked", "Victim Gender" = "Victim.gender",
                   "Victim Injury" = "Victim.injury", "Injury Severity" = "Injury.severity", "Site Category" = "Site.category", "Victim Activity" = "Victim.activity"), selected = "Victim.injury")

radioButtons("prop_count", label = h3("Proportions or Count:"), 
                   choices = list("Proportion" = "prop", "Count" = "count"))

checkboxInput("error_bar", label = h4("Include Error Bar"))

```


<!-- Where are Shark Attacks Occuring? -->
<!-- =====================================   -->

<!-- ```{r} -->
<!-- #loading in the sf data -->

<!-- #removing the spaces in the latitude and longitude data that causes errors -->
<!-- shark_attacks_fixed_latlon <- shark_attacks %>% -->
<!--   mutate(Latitude = str_replace_all(Latitude, "\\s+", "")) %>% -->
<!--   mutate(Longitude = str_replace_all(Longitude, "\\s+", "")) %>% -->
<!--   mutate(Latitude = as.numeric(Latitude)) %>% -->
<!--   mutate(Longitude = as.numeric(Longitude)) %>% -->
<!--   filter(is.na(Latitude) == F) %>% -->
<!--   filter(is.na(Longitude) == F) -->


<!-- # To make the map with points -->
<!-- shark_attacks_sf <- shark_attacks_fixed_latlon %>% -->
<!--   st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) %>% -->
<!--   st_transform(crs = 3577) -->


<!-- #crop the australia polygon  -->
<!-- aus_shp <- st_crop(aus_shp, xmin = 113, ymin = -43.9, xmax = 153.9, ymax = -10) #100, ymin = -46, xmax = 160, ymax = -12)    -->

<!-- #aus_shp <- aus_shp$geometry #assigning only the geometry of the states -->
<!-- aus_shp <- st_as_sf(st_transform(aus_shp, crs = 3577)) -->

<!-- #filtering out other territories -->
<!-- aus_shp <- aus_shp %>% -->
<!--   filter(STE_NAME21 != "Other Territories") -->




<!-- ``` -->

<!-- Sidebar {.sidebar} -->
<!-- ----------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- #widgets for the map of australia  -->

<!-- # sliderInput("point_transp", label = h3("Point Transparency"), min = 0,  -->
<!-- #         max = 5, value = 1, step = 0.1) -->
<!-- #  -->
<!-- # sliderInput("point_size", label = "Point size:", -->
<!-- #              min = 0.5, max = 3, value = 2, step = 0.5) -->

<!-- radioButtons("response_var_map", label = h3("Attack Characteristic:"), -->
<!--     choices = list("Victim Injury" = "Victim.injury", "Site Category" = "Site.category", "Provoked?" = "Provoked.unprovoked", "Victim Activity" = "Victim.activity","Injury Severity" = "Injury.severity", "Victim Gender" = "Victim.gender"), selected = "Victim.injury") -->

<!-- # radioButtons("response_var_map", label = h3("Attack Characteristic:"), -->
<!-- #     choices = list("New South Wales" = "Victim.injury", "Site Category" = "Site.category", "Provoked?" = "Provoked.unprovoked", "Victim Activity" = "Victim.activity","Injury Severity" = "Injury.severity", "Victim Gender" = "Victim.gender"), selected = "Victim.injury") -->





<!-- ``` -->

<!-- Column  -->
<!-- ----------------------------------------------------------------------- -->

<!-- ```{r} -->

<!-- aus_shp <- sf::st_cast(aus_shp, "MULTIPOLYGON") #group_or_split = T -->
<!-- shark_attacks_sf <- sf::st_cast(shark_attacks_sf, "MULTIPOINT") -->

<!-- renderPlotly({ -->
<!--   map <- ggplot()+ -->
<!--     geom_sf(data = aus_shp, aes(fill = STE_NAME21)) + -->
<!--     labs(x = "", y = "", fill = "State") + -->
<!--     geom_sf_text(data = aus_shp, aes(label = STE_NAME21), color = "black", size = 2, check_overlap = T) + -->
<!--     geom_sf(data = shark_attacks_sf, aes(fill = .data[[input$response_var_map]], text = paste0("Date: ", paste(Incident.month, Incident.year, sep = "/"),  -->
<!--                       "<br>Location: ", Location, -->
<!--                       "<br>Victim Activity:" , Victim.activity, -->
<!--                       "<br>Injury Type: ", Victim.injury, -->
<!--                       "<br>Victim Gender: ", Victim.gender, -->
<!--                       "<br>Site Category: ", Site.category, -->
<!--                       "<br>Injury Severity: ", Injury.severity)),  -->
<!--           size = 1.5) + -->
<!--     scale_color_manual(values = c("Fatal" = "#a50f15", "Injured" = "#ef3b2c", "Uninjured" = "#fcbba1", "Island Open Ocean" = "#045a8d", "Estuary/Habor" = "#2b8cbe", "Coastal" = "#74a9cf",  "River" = "#a6bddb", "Other: Fish Farm" = "#d0d1e6","Provoked" = "#8c3a40", "Unprovoked" = "#343d6b", "Swimming" = "#a6cee3", "Boarding" = "#1f78b4", "Spearfishing" = "#b2df8a", "Snorkeling" = "#33a02c", "Diving" = "#fb9a99", "Boating" = "#e31a1c", "Standing in Water" = "#fdbf6f", "Fishing" = "#ff7f00", "Other" = "#cab2d6", -->
<!--           "Major Lacerations" = "#a50f15", "Minor Lacerations" = "#de2d26", "Punctures" = "#fb6a4a" , "Surface Wound" = "#fc9272", "Abrasion" = "#fcbba1", "Other: Teeth Marks" = "#fee5d9", "Male" = "#a6cee3", "Female" = "#fb9a99"))+ -->

<!--        scale_fill_manual(values = c("Fatal" = "#a50f15", "Injured" = "#ef3b2c", "Uninjured" = "#fcbba1", "Island Open Ocean" = "#045a8d", "Estuary/Habor" = "#2b8cbe", "Coastal" = "#74a9cf",  "River" = "#a6bddb", "Other: Fish Farm" = "#969696","Provoked" = "#8c3a40", "Unprovoked" = "#343d6b", "Swimming" = "#a6cee3", "Boarding" = "#1f78b4", "Spearfishing" = "#b2df8a", "Snorkeling" = "#33a02c", "Diving" = "#fb9a99", "Boating" = "#e31a1c", "Standing in Water" = "#fdbf6f", "Fishing" = "#ff7f00", "Other" = "#cab2d6", -->
<!--           "Major Lacerations" = "#a50f15", "Minor Lacerations" = "#de2d26", "Punctures" = "#fb6a4a" , "Surface Wound" = "#fc9272", "Abrasion" = "#fcbba1", "Other: Teeth Marks" = "#fee5d9", "Male" = "#a6cee3", "Female" = "#fb9a99")) + -->
<!--       interactive_theme -->


<!--   return(ggplotly(map)) -->

<!-- }) -->


<!-- ``` -->





