---
title: "Body parts page"
date: "11/24/24"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny

---

Which body part are you most likely to injure?
=====================================  

```{r global_body, include=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(flexdashboard)
library(plotly)
library(stringr)
library(devtools)
install_github("josedv82/bdgramR")
library(bdgramR)

shark <- read.csv("Shark Dataset.csv")

interactive_theme <- theme_gray() +# White background, black and white theme
  theme(plot.title = element_text(family = "Georgia", face = "bold", color = "#0a144a"),
        axis.title = element_text(family = "DIN Alternate", color = "#0a144a"),
        axis.text = element_text(color = "#0a144a"),
        legend.title = element_text(family = "DIN Alternate", face = "bold",  color = "#0a144a"),
        legend.text = element_text(family = "DIN Alternate", color = "#0a144a"),
        legend.box.margin = margin(6, 6, 6, 6),
        legend.background = element_rect(fill = "#d1d4e3"),
        panel.background = element_rect(fill = "#d1d4e3"),
        plot.background = element_rect(fill = "#d1d4e3"))
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput("gender_EL", label = "Select a gender", 
            choices =  c("All" = "all",
                         "Male" = "male",
                         "Female" = "female"))

sliderInput("age_EL", label = "Select your age",
            min = 0, max = 75, value = 30, step = 1)

radioButtons("bar_EL", "Bar Chart type",
               c("Bar chart of all age ranges" = "all",
                 "Bar chart of your age range" = "specific"))


```

Data source: Australian Shark-Incident Database

Row {data-height=100}
-----------------------------------------------------------------------

### Looks like...
Watch out for your legs! They seem to be the most common part of the body injured by people.

Row 
-----------------------------------------------------------------------
### Body part injuries by age chunk

```{r}
renderPlot({
  
body_injury <- shark %>%
  mutate(body_1 = str_split_fixed(Injury.location, ", ", 4)[ ,1],
         body_2 = str_split_fixed(Injury.location, ", ", 4)[ ,2],
         body_3 = str_split_fixed(Injury.location, ", ", 4)[ ,3],
         body_4 = str_split_fixed(Injury.location, ", ", 4)[ ,4],
         age_range = case_when(Victim.age <= 10 ~ "0-10", 
                              (10 < Victim.age) & (Victim.age <= 20)  ~ "11-20",
                              (20 < Victim.age) & (Victim.age <= 30)  ~ "21-30",
                              (30 < Victim.age) & (Victim.age <= 40)  ~ "31-40",
                              (40 < Victim.age) & (Victim.age <= 50)  ~ "41-50",
                              (50 < Victim.age) & (Victim.age <= 60)  ~ "51-60",
                              (60 < Victim.age) & (Victim.age <= 70)  ~ "61-70",
                              (70 < Victim.age) & (Victim.age <= 75)  ~ "71-75",
                              Victim.age == " "                ~ NA)) 
if (input$gender_EL == "all") { #if it's all genders
  
} else { #if it's a specific gender
  body_injury <- body_injury %>% 
    filter(Victim.gender == input$gender_EL)
}

body_1 <- body_injury %>% 
  group_by(body_1, age_range) %>% 
  rename(body = body_1) %>% 
  filter(body != "") %>% 
  summarize(sum = n())

body_2 <- body_injury %>% 
  group_by(body_2, age_range) %>% 
  rename(body = body_2) %>% 
  filter(body != "") %>% 
  summarize(sum = n())

body_3 <- body_injury %>% 
  group_by(body_3, age_range) %>% 
  rename(body = body_3) %>% 
  filter(body != "") %>% 
  summarize(sum = n())

body_4 <- body_injury %>% 
  group_by(body_4, age_range) %>% 
  rename(body = body_4) %>% 
  filter(body != "") %>% 
  summarize(sum = n())

body_12 <- rbind(body_1, body_2)
body_123 <- rbind(body_12, body_3)
body_1234 <- rbind(body_123, body_4)

body_total <- body_1234 %>% 
  group_by(body, age_range) %>%
  mutate(body = ifelse(body == "left leg", "leg", body),
         body = ifelse(body == "left foot", "foot", body)) %>% 
  summarize(Number_injury = sum(sum)) %>% 
  mutate(overall = case_when(body == "ankle" ~ "foot",
                            body == "calf" ~ "leg",
                            body == "hand" ~ "arm",
                            body == "leg" ~ "leg",
                            body == "other: half of body recovered" ~ "",
                            body == "other: uninjured" ~ "",
                            body == "right" ~ "",
                            body == "shoulder " ~ "shoulder",
                            body == "torso" ~ "torso",
                            body == "arm" ~ "arm",
                            body == "foot" ~ "foot",
                            body == "head" ~ "head",
                            body == "other: body not recovered" ~ "",
                            body == "other: multiple bites" ~ "",
                            body == "pelvic region" ~ "pelvic region",
                            body == "shoulder" ~ "shoulder",
                            body == "thigh" ~ "leg"),
         body = ifelse(grepl("other", body, fixed = TRUE), "", body)) %>% 
  filter(overall != "" ) %>% 
  na.omit()

final_body_bar <- body_total %>% 
    group_by(age_range) %>% 
  filter(Number_injury == max(Number_injury))

final_body_bar$age_range <- factor(final_body_bar$age_range, levels = c("0-10", "11-20", "21-30", "31-40", "41-50", "51-60", "61-70", "71-75"))

body_bar <- ggplot(final_body_bar, aes(x = age_range, y = Number_injury, fill = body)) +
  geom_col() +
  labs(x = "Age Range",
       y = "Number of Injuries for this Body Part",
       title = "Which Body Part was Most Injured by Age Ranges?",
       fill = "Body Part Injured") +
  scale_fill_manual(values = c("#44AA99", "#CC6677", "#493C86", "#DDCC77"))

if (input$bar_EL == "all") { #if it's all barchart
    
 specific_age <- final_body_bar %>% 
  filter(age_range == case_when(input$age_EL <= 10 ~ "0-10", 
                              (10 < input$age_EL) & (input$age_EL <= 20)  ~ "11-20",
                              (20 < input$age_EL) & (input$age_EL <= 30)  ~ "21-30",
                              (30 < input$age_EL) & (input$age_EL <= 40)  ~ "31-40",
                              (40 < input$age_EL) & (input$age_EL <= 50)  ~ "41-50",
                              (50 < input$age_EL) & (input$age_EL <= 60)  ~ "51-60",
                              (60 < input$age_EL) & (input$age_EL <= 70)  ~ "61-70",
                              (70 < input$age_EL) & (input$age_EL <= 75)  ~ "71-75"))

body_bar + geom_col(data = specific_age, color = "#a50f15", size = 1.5) + 
  guides(color = "none") +
  interactive_theme
  
} else { #if it's a specific age barchart

body_total_age <- body_total %>% 
  group_by(body) %>% 
  filter(age_range == case_when(input$age_EL <= 10 ~ "0-10", 
                               (10 < input$age_EL) & (input$age_EL <= 20)  ~ "11-20",
                               (20 < input$age_EL) & (input$age_EL <= 30)  ~ "21-30",
                               (30 < input$age_EL) & (input$age_EL <= 40)  ~ "31-40",
                               (40 < input$age_EL) & (input$age_EL <= 50)  ~ "41-50",
                               (50 < input$age_EL) & (input$age_EL <= 60)  ~ "51-60",
                               (60 < input$age_EL) & (input$age_EL <= 70)  ~ "61-70",
                               (70 < input$age_EL) & (input$age_EL <= 75)  ~ "71-75"))

body_bar <- ggplot(body_total_age, aes(x = reorder(body, Number_injury), y = Number_injury)) +
  geom_col(fill = "#a50f15") +
  labs(x = "Body Part Injured",
       y = "Number of Injuries for this Body Part",
       title = paste("Which Body Part was Most Injured in Ages", case_when(input$age_EL <= 10 ~ "0-10", 
                               (10 < input$age_EL) & (input$age_EL <= 20)  ~ "11-20",
                               (20 < input$age_EL) & (input$age_EL <= 30)  ~ "21-30",
                               (30 < input$age_EL) & (input$age_EL <= 40)  ~ "31-40",
                               (40 < input$age_EL) & (input$age_EL <= 50)  ~ "41-50",
                               (50 < input$age_EL) & (input$age_EL <= 60)  ~ "51-60",
                               (60 < input$age_EL) & (input$age_EL <= 70)  ~ "61-70",
                               (70 < input$age_EL) & (input$age_EL <= 75)  ~ "71-75")),
       fill = "Body Part Injured") +
  interactive_theme

body_bar
}

})
```

### Data points from your specific age

```{r}
renderPlot({
  
body_polygon <- bdgramr(data = data, model = "basic_male") 

body_injury <- shark %>%
  mutate(body_1 = str_split_fixed(Injury.location, ", ", 4)[ ,1],
         body_2 = str_split_fixed(Injury.location, ", ", 4)[ ,2],
         body_3 = str_split_fixed(Injury.location, ", ", 4)[ ,3],
         body_4 = str_split_fixed(Injury.location, ", ", 4)[ ,4]) %>% 
    filter(Victim.age == as.numeric(input$age_EL))

if (input$gender_EL == "all") { #if the shark species is all
  
} else {
  body_injury <- body_injury %>% 
    filter(Victim.gender == input$gender_EL)
}

body_1 <- body_injury %>% 
  group_by(body_1) %>% 
  rename(body = body_1) %>% 
  filter(body != "") %>% 
  summarize(sum = n())

body_2 <- body_injury %>% 
  group_by(body_2) %>% 
  rename(body = body_2) %>% 
  filter(body != "") %>% 
  summarize(sum = n())

body_3 <- body_injury %>% 
  group_by(body_3) %>% 
  rename(body = body_3) %>% 
  filter(body != "") %>% 
  summarize(sum = n())

body_4 <- body_injury %>% 
  group_by(body_4) %>% 
  rename(body = body_4) %>% 
  filter(body != "") %>% 
  summarize(sum = n())

body_12 <- rbind(body_1, body_2)
body_123 <- rbind(body_12, body_3)
body_1234 <- rbind(body_123, body_4)

body_total <- body_1234 %>% 
  group_by(body) %>%
  summarize(Number_injury = sum(sum)) %>% 
  mutate(body = ifelse(body == "left leg", "leg", body),
         body = ifelse(body == "left foot", "foot", body),
         overall = case_when(body == "ankle" ~ "foot",
                            body == "calf" ~ "leg",
                            body == "hand" ~ "arm",
                            body == "leg" ~ "leg",
                            body == "other: half of body recovered" ~ "",
                            body == "other: uninjured" ~ "",
                            body == "right" ~ "",
                            body == "shoulder " ~ "shoulder",
                            body == "torso" ~ "torso",
                            body == "arm" ~ "arm",
                            body == "foot" ~ "foot",
                            body == "head" ~ "head",
                            body == "other: body not recovered" ~ "torso",
                            body == "other: multiple bites" ~ "torso",
                            body == "pelvic region" ~ "pelvic region",
                            body == "shoulder" ~ "shoulder",
                            body == "thigh" ~ "leg")) %>% 
  filter(overall != "") 

body_polygon <- bdgramr(data = data, model = "basic_male") %>% 
  mutate(body = case_when(Muscle == "Head" ~ "head",
                          Muscle == "Pectoral" ~ "shoulder",
                          Muscle == "Intercostal" ~ "torso",
                          Muscle == "Abdominal" ~ "pelvic region",
                          Muscle == "Quadriceps" ~ "thigh",
                          Muscle == "Foot" ~ "foot",
                          Muscle == "Shoulder" ~ "shoulder",
                          Muscle == "Lower_back" ~ "torso",
                          Muscle == "Hamstring" ~ "thigh",
                          Muscle == "Clavicle" ~ "neck",
                          Muscle == "Arm" ~ "arm",
                          Muscle == "Forearm" ~ "arm",
                          Muscle == "Hand" ~ "hand",
                          Muscle == "Shin" ~ "calf",
                          Muscle == "Neck" ~ "neck",
                          Muscle == "Upper_back" ~ "torso",
                          Muscle == "Gluteus_Maximus" ~ "pelvic region",
                          Muscle == "Calf" ~ "calf"))

body_combine <- full_join(body_polygon, body_total, by = "body", relationship = "many-to-many")


ggplot(data = body_combine, aes(x,y, group = Id)) +
  geom_bdgramr(color = "#67000d", aes(fill = Number_injury)) +
  scale_fill_gradient(low = "#fff5f0", high = "#a50f15" ) +
  labs(title = paste("Which body part was most injured at age", input$age_EL, "?"),
       caption = "BdygramR: original_male diagram",
       fill = "Number of Injuries") +
  interactive_theme

})
```