---
title: "Where are shark attacks occuring?"
output: flexdashboard::flex_dashboard
runtime: shiny
---

# Loading in the Data and Packages
```{r global, include=FALSE, warning=FALSE, message=FALSE}
shark_attacks <- read.csv("Australian Shark-Incident Database Public Version.csv")
                          #"Shark Dataset.csv



# load packages in 'global' chunk so they can be shared by all users of the dashboard
library(httr2)
library(purrr)
library(tibble)
library(lubridate)
library(dplyr)
library(ggplot2)
library(shiny)
library(tidyr)
library(stringr)
library(tidyverse)

#shapefiles
library(sf)
library(maps)


# reading in the Australian state shapefiles

aus_shp <-st_read("./STE_2021_AUST_SHP_GDA94/STE_2021_AUST_GDA94.shp", stringsAsFactors=FALSE, quiet=TRUE)
#save(aus_shp, file="./aus_shp.RData")
#load("aus_shp.RData")

tourist_regions <-st_read("./TR_2021_AUST_GDA94_SHP/TR_2021_AUST_GDA94.shp", stringsAsFactors=FALSE, quiet=TRUE)

```



# cleaning the data

```{r}

#adding in means
shark_attacks <- shark_attacks %>%
  filter(is.na(UIN) != T) %>% #removing the empty rows
  mutate(Victim.injury = case_when(Victim.injury == "fatal" ~ "Fatal",
                                   Victim.injury == "injured" ~ "Injured",
                                   Victim.injury == "Injured" ~ "Injured",
                                   Victim.injury == "uninjured" ~ "Uninjured")) %>%
  mutate(Provoked.unprovoked = case_when(Provoked.unprovoked == "provoked" ~ "Provoked",
                                   Provoked.unprovoked == "unprovoked" ~ "Unprovoked")) %>%
  mutate(Victim.gender = case_when(Victim.gender == "female" ~ "Female",
                                   Victim.gender == "male" ~ "Male")) %>%
  mutate(Injury.severity = case_when(Injury.severity == "abrasion" ~ "Abrasion", Injury.severity == "major lacerations" ~ "Major Lacerations", Injury.severity == "minor lacerations" ~ "Minor Lacerations", Injury.severity == "other: teeth marks" ~ "Other: Teeth Marks", Injury.severity == "punctures" ~ "Punctures", Injury.severity == "surface wound" ~ "Surface Wound")) %>%
  mutate(Site.category = case_when(Site.category == "coastal" ~ "Coastal",
                                   Site.category == "Coastal" ~ "Coastal",
                                   Site.category == "estuary/harbour" ~ "Estuary/Harbour",
                                   Site.category == "island open ocean" ~ "Island Open Ocean", 
                                   Site.category == "ocean/pelagic" ~ "Ocean/Pelagic",
                                   Site.category == "other: fish farm" ~ "Other: Fish Farm",
                                   Site.category == "river" ~ "River")) %>%
  filter(Incident.year != "1791") %>%
  mutate(Victim.activity = case_when(Victim.activity == "boarding" ~ "Boarding",
                                   Victim.activity == "diving" ~ "Diving",
                                   Victim.activity == "fishing" ~ "Fishing",
                                   Victim.activity == "motorised boating" ~ "Motorised Boating",
                                   Victim.activity == "other: standing in water" ~ "Standing in Water",
                                   Victim.activity == "other:floating" ~ "Floating",
                                   Victim.activity == "snorkeling" ~ "Snorkeling", 
                                   Victim.activity == "spearfishing" ~ "Spearfishing",
                                   Victim.activity == "swimming" ~ "Swimming",
                                   Victim.activity == "unmotorised boating" ~ "Unmotorised Boating")) %>%
  filter(Incident.year != "1791") %>%
  group_by(Incident.year) %>%
   #creating mean columns
  mutate(Shark.length.m.mean = mean(Shark.length.m)) %>%
  mutate(No.sharks.mean = mean(No.sharks)) %>%
  mutate(Victim.age.mean = mean(Victim.age)) %>%
  #creating date groupings
  mutate(Year = case_when((Incident.year > 1800 & Incident.year <= 1850) ~ "1800-1850", 
                          (Incident.year > 1850 & Incident.year <= 1900) ~ "1850-1900",
                          (Incident.year > 1900 & Incident.year <= 1950) ~ "1900-1950",
                          (Incident.year > 1950 & Incident.year <= 2000) ~ "1950-2000",
                          (Incident.year > 2000 & Incident.year <= 2022) ~ "2000-2022")) 

#counting the number of sharks every 50 years
shark_attacks <- shark_attacks %>%
  group_by(Year) %>%
  mutate(Number_Attacks = n())
```


```{r}

#calculating the counts for each location

shark_attacks <- shark_attacks %>%
  mutate(State_full = case_when(State == "SA" ~ "South Australia",
                                State == "TAS" ~ "Tasmania",
                                State == "VIC" ~ "Victoria",
                                State == "WA" ~ "Western Australia",
                                State == "QLD" ~ "Queensland",
                                State == "NSW" ~ "New South Wales",
                                State == "NT" ~ "Northern Territory"))

```


```{r}
#loading in the sf data

#removing the spaces in the latitude and longitude data that causes errors
shark_attacks_fixed_latlon <- shark_attacks %>%
  mutate(Latitude = str_replace_all(Latitude, "\\s+", "")) %>%
  mutate(Longitude = str_replace_all(Longitude, "\\s+", "")) %>%
  mutate(Latitude = as.numeric(Latitude)) %>%
  mutate(Longitude = as.numeric(Longitude)) %>%
  filter(is.na(Latitude) == F) %>%
  filter(is.na(Longitude) == F)


# To make the map with points
shark_attacks_sf <- shark_attacks_fixed_latlon %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) %>%
  st_transform(crs = 3577)


#crop the australia polygon 
aus_shp <- st_crop(aus_shp, xmin = 113, ymin = -43.9, xmax = 153.9, ymax = -10) #100, ymin = -46, xmax = 160, ymax = -12)   

#aus_shp <- aus_shp$geometry #assigning only the geometry of the states
aus_shp <- st_as_sf(st_transform(aus_shp, crs = 3577))

#filtering out other territories
aus_shp <- aus_shp %>%
  filter(STE_NAME21 != "Other Territories")


#plotting the australia map
ggplot()+
  geom_sf(data = shark_attacks_sf, color = "red") + 
  geom_sf(data = aus_shp$geometry)


```

plotting

```{r}

#plotting the australia map
ggplot()+
  geom_sf(data = shark_attacks_sf, aes(color = Incident.year)) +
  geom_sf(data = aus_shp$geometry)


```


```{r}

#creating a dataframe for counts and proportions by state
shark_attacks_counts_state <- shark_attacks %>%
  group_by(State_full) %>%
  summarise(count_attacks_state = n(), 
            total_attacks = nrow(shark_attacks),
            proportion_attacks_state = count_attacks_state / total_attacks, 
            std_error_attacks_state = sqrt(proportion_attacks_state * (1-proportion_attacks_state) / total_attacks),  #  compute standard error of each proportion
         lower_attacks_state = proportion_attacks_state - 1.96 * std_error_attacks_state,  #  compute CI lower bound
         upper_attacks_state = proportion_attacks_state + 1.96 * std_error_attacks_state)

#creating a dataframe for counts and proportions by site category
shark_attacks_counts_site <- shark_attacks %>%
  group_by(Site.category) %>%
  summarise(count_attacks_site = n(), 
            total_attacks = nrow(shark_attacks),
            proportion_attacks_site = count_attacks_site / total_attacks, 
            std_error_attacks_site = sqrt(proportion_attacks_site * (1-proportion_attacks_site) / total_attacks),  #  compute standard error of each proportion
         lower_site = proportion_attacks_site - 1.96 * std_error_attacks_site,  #  compute CI lower bound
         upper_site = proportion_attacks_site + 1.96 * std_error_attacks_site) %>%
  filter(is.na(Site.category) == F)

#creating a dataframe for counts and proportions by location
shark_attacks_counts_location <- shark_attacks %>%
  group_by(Location) %>%
  summarise(count_attacks_location = n(), 
            total_attacks = nrow(shark_attacks),
            proportion_attacks_location = count_attacks_location / total_attacks, 
            std_error_attacks_location = sqrt(proportion_attacks_location * (1-proportion_attacks_location) / total_attacks),  #  compute standard error of each proportion
         lower_location = proportion_attacks_location - 1.96 * std_error_attacks_location,  #  compute CI lower bound
         upper_location = proportion_attacks_location + 1.96 * std_error_attacks_site) %>%
  filter(is.na(std_error_attacks_location) == F)
            


#barcharts by area

#state

#counts by state
ggplot(data = shark_attacks_counts_state, aes(x = fct_rev(fct_reorder(State_full, count_attacks_state,  .desc = T)), y =count_attacks_state, fill = State_full)) +
  geom_bar(stat = "identity") + 
  labs(x = "States", fill = "States", y = "Number of Shark Attacks") + 
  coord_flip() 

#proportions by state
ggplot(data = shark_attacks_counts_state, aes(x = fct_rev(fct_reorder(State_full, proportion_attacks_state,  .desc = T)), y = proportion_attacks_state, fill = State_full)) +
  geom_bar(stat = "identity") + 
  labs(x = "States", fill = "States", y = "Proportion of Shark Attacks") + 
  coord_flip() 

#site category

#counts by site category
ggplot(data = shark_attacks_counts_site, aes(x = fct_rev(fct_reorder(Site.category, count_attacks_site,  .desc = T)), y =count_attacks_site, fill = Site.category)) +
  geom_bar(stat = "identity") + 
  labs(x = "Site Category", fill = "Site Category", y = "Number of Shark Attacks") + 
  coord_flip() 

#proportions by site category
ggplot(data = shark_attacks_counts_site, aes(x = fct_rev(fct_reorder(Site.category, proportion_attacks_site,  .desc = T)), y = proportion_attacks_site, fill = Site.category)) +
  geom_bar(stat = "identity") + 
  labs(x = "Site Category", fill = "Site Category", y = "Proportion of Shark Attacks") + 
  coord_flip() 

#location

#counts by location
ggplot(data = shark_attacks_counts_site, aes(x = fct_rev(fct_reorder(Site.category, count_attacks_site,  .desc = T)), y =count_attacks_site, fill = Site.category)) +
  geom_bar(stat = "identity") + 
  labs(x = "Site Category", fill = "Site Category", y = "Number of Shark Attacks") + 
  coord_flip() 

#proportions by location
ggplot(data = shark_attacks_counts_site, aes(x = fct_rev(fct_reorder(Site.category, proportion_attacks_site,  .desc = T)), y = proportion_attacks_site, fill = Site.category)) +
  geom_bar(stat = "identity") + 
  labs(x = "Site Category", fill = "Site Category", y = "Proportion of Shark Attacks") + 
  coord_flip() 

```

```{r}


#widgets for the barcharts

radioButtons("response_var", label = h3("Attack Characteristic:"), 
    choices = list("Number of Attacks" = "attack_count", "Victim Age" = "Victim.age", "Victim Injury" = "Victim.injury", "Site Category" = "Site.category", "Provoked?" = "Provoked.unprovoked", "Victim Activity" = "Victim.activity","Injury Severity" = "Injury.severity", "Victim Gender" = "Victim.gender"), selected = "Victim.injury")

radioButtons("prop_count", label = h3("Proportions or Count:"), 
                   choices = list("Proportion" = "prop", "Count" = "count"))

checkboxInput("error_bar", label = h4("Include Error Bar"))

```


Where are Shark Attacks Occuring?
=====================================  

Sidebar {.sidebar}
-----------------------------------------------------------------------

```{r}
#widgets for the map of australia 

# sliderInput("point_transp", label = h3("Point Transparency"), min = 0, 
#         max = 5, value = 1, step = 0.1)
# 
# sliderInput("point_size", label = "Point size:",
#              min = 0.5, max = 3, value = 2, step = 0.5)

radioButtons("response_var_map", label = h3("Attack Characteristic:"),
    choices = list("Victim Injury" = "Victim.injury", "Site Category" = "Site.category", "Provoked?" = "Provoked.unprovoked", "Victim Activity" = "Victim.activity","Injury Severity" = "Injury.severity", "Victim Gender" = "Victim.gender"), selected = "Victim.injury")

#"Victim Age" = "Victim.age", "Shark Length" = "Shark.length.m", "Number of Sharks During the Attacks" = "No.sharks", 

```

Column 
-----------------------------------------------------------------------

```{r}

aus_shp <- sf::st_cast(aus_shp, "MULTIPOLYGON") #group_or_split = T
shark_attacks_sf <- sf::st_cast(shark_attacks_sf, "MULTIPOINT")

renderPlotly({
  map <- ggplot()+
    geom_sf(data = aus_shp, aes(fill = STE_NAME21)) +
    labs(x = "", y = "", fill = "State") +
    geom_sf_text(data = aus_shp, aes(label = STE_NAME21), color = "black", size = 2, check_overlap = T) +
    geom_sf(data = shark_attacks_sf, aes(fill = .data[[input$response_var_map]], text = paste0("Date: ", paste(Incident.month, Incident.year, sep = "/"), 
                      "<br>Location: ", Location,
                      "<br>Victim Activity:" , Victim.activity,
                      "<br>Injury Type: ", Victim.injury,
                      "<br>Victim Gender: ", Victim.gender,
                      "<br>Site Category: ", Site.category,
                      "<br>Injury Severity: ", Injury.severity)), 
          size = 1.5) +
    scale_color_manual(values = c("Fatal" = "#a50f15", "Injured" = "#ef3b2c", "Uninjured" = "#fcbba1", "Island Open Ocean" = "#045a8d", "Estuary/Habor" = "#2b8cbe", "Coastal" = "#74a9cf",  "River" = "#a6bddb", "Other: Fish Farm" = "#d0d1e6","Provoked" = "#8c3a40", "Unprovoked" = "#343d6b", "Swimming" = "#a6cee3", "Boarding" = "#1f78b4", "Spearfishing" = "#b2df8a", "Snorkeling" = "#33a02c", "Diving" = "#fb9a99", "Boating" = "#e31a1c", "Standing in Water" = "#fdbf6f", "Fishing" = "#ff7f00", "Other" = "#cab2d6",
          "Major Lacerations" = "#a50f15", "Minor Lacerations" = "#de2d26", "Punctures" = "#fb6a4a" , "Surface Wound" = "#fc9272", "Abrasion" = "#fcbba1", "Other: Teeth Marks" = "#fee5d9", "Male" = "#a6cee3", "Female" = "#fb9a99"))+

       scale_fill_manual(values = c("Fatal" = "#a50f15", "Injured" = "#ef3b2c", "Uninjured" = "#fcbba1", "Island Open Ocean" = "#045a8d", "Estuary/Habor" = "#2b8cbe", "Coastal" = "#74a9cf",  "River" = "#a6bddb", "Other: Fish Farm" = "#969696","Provoked" = "#8c3a40", "Unprovoked" = "#343d6b", "Swimming" = "#a6cee3", "Boarding" = "#1f78b4", "Spearfishing" = "#b2df8a", "Snorkeling" = "#33a02c", "Diving" = "#fb9a99", "Boating" = "#e31a1c", "Standing in Water" = "#fdbf6f", "Fishing" = "#ff7f00", "Other" = "#cab2d6",
          "Major Lacerations" = "#a50f15", "Minor Lacerations" = "#de2d26", "Punctures" = "#fb6a4a" , "Surface Wound" = "#fc9272", "Abrasion" = "#fcbba1", "Other: Teeth Marks" = "#fee5d9", "Male" = "#a6cee3", "Female" = "#fb9a99")) +
      interactive_theme
    
  
  return(ggplotly(map))

})


```



